install.packages("readxl")
library(readxl)
pokemon = read_excel(path = "L:/BUT/SD/Promo 2023/bfontaine/R/CSV/pokemon.xlsx",sheet = "pokemon")
dim(pokemon)
ncol(pokemon)
nrow(pokemon)
summary(pokemon)
pokemon$is_legendary =as.factor(pokemon$is_legendary)
pokemon$generation =as.factor(pokemon$generation)
pokemon$type =as.factor(pokemon$type)
summary(pokemon)
median=median(pokemon$attack)
pokemon$attack_group = ifelse(pokemon$attack >= median,"attack+","attack-")
pokemon$attack_group = as.factor(pokemon$attack_group)
summary(pokemon$attack_group)
pokemon$water_fire = ifelse(pokemon$type %in% c("water","fire"),"yes","no")
pokemon$water_fire =as.factor(pokemon$water_fire)
summary(pokemon$water_fire)
View(pokemon)
attackquant= quantile(pokemon$attack, probs=0.75)
defensequant= quantile(pokemon$defense, probs=0.75)
speedquant= quantile(pokemon$speed, probs=0.75)
pokemon$doumbe = ifelse(pokemon$attack > attackquant & pokemon$defense > defensequant & pokemon$speed > speedquant, "yes", "no")
pokemon$doumbe = as.factor(pokemon$doumbe)
summary(pokemon$doumbe)
requete = subset(pokemon, is.na(weight_kg))
View(requete)
requete = subset(pokemon, !is.na(weight_kg))
View(requete)